import type {Metadata} from 'next'
import {Playfair_Display} from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

export const metadata: Metadata = {
  title: 'MUELLER WAGNER',
  description: 'Generated by create next app',
}

const playfairDisplay = Playfair_Display({
  weight: ['400', '600'],
  subsets: ['latin', 'cyrillic'],
  variable: '--font-playfair-display',
})

const kaius = localFont({
  src: [{path: '../assets/fonts/Kaius-Bold.woff2', weight: '700'}],
  variable: '--font-kaius',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={`bg-white text-foreground font-playfair antialiased ${playfairDisplay.variable} ${kaius.variable}`}>{children}</body>
    </html>
  )
}
