import type {Metadata} from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'MUELLER WAGNER',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className="font-sans antialiased bg-white text-foreground">{children}</body>
    </html>
  )
}
